<a href="https://colab.research.google.com/github/tjsoliveira/intro_tensorflow/blob/main/tensorflow_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TensorFlow**

In [4]:
from __future__ import absolute_import, division, print_function, unicode_literals

# Install TensorFlow
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

import tensorflow as tf

# **Tensor**

É um vetor n-dimensional usado para representar conjuntos de dados com múltiplas dimensões.

À medida que a dimensão cresce, os dados tornam-se mais complexos. Tensores podemm ser **constantes** ou **variáveis**.


In [2]:
# Escalar: tensor rank 0 com formmto [ ]
escalar = 3

# Vetor: tensor rank 1 com formato [3] - 3 linhas
vetor = [1, 2, 3]

# Matriz: tensor rank 2 com formato [2, 3] - 2 linhas e 3 colunas
matriz = [[1,2 ,3], [4, 5, 6]]

# Tensor: tensor rank 3 com formato [2, 1, 3]
tensor = [[[1, 2, 3]], [[7, 8, 9]]]

[[[1, 2, 3]], [[7, 8, 9]]]

In [61]:
# Criando um Tensor Rank 4
tensor = tf.zeros(shape=[2, 3, 4, 5])
tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [16]:
# Criando uma matriz de zeros
matriz_0 = tf.zeros(shape=(2, 2))
# Criando uma matriz
matriz_1 = tf.ones(shape=(2, 2))

# Somando a soma de todos os elementos da matriz_1
tf.reduce_sum(matriz_1).numpy()

4.0

**Atributos de um Tensor**

In [73]:
print('Tipo de Dado: ', tensor.dtype)

print('Número de dimensões: ', tensor.ndim)

print('Formato do Tensor: ', tensor.shape)

print('Elementos do Eixo 0: ', tensor.shape[0])

print('Elementos do último Eixo: ', tensor.shape[-1])

print('Total de Elementos: ', tf.size(tensor).numpy())

Tipo de Dado:  <dtype: 'float32'>
Número de dimensões:  4
Formato do Tensor:  (2, 3, 4, 5)
Elementos do Eixo 0:  2
Elementos do último Eixo:  5
Total de Elementos:  120


In [76]:
# Os dois primeiros itens de cada dimensão'
tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [77]:
# Obtém a dimensão de cada índice, exceto o final
tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [80]:
# Obtém o último item de cada linha
tensor[:, -1]

<tf.Tensor: shape=(2, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

# Grafo Computacional

Grafos são modelos matemáticos para resolver problemas práticos do dia a dia, com várias aplicações no mundo real como: circuitos elétricos, redes de distribuição, relações de parentesco entre pessoas, análise de redes sociais, entre outros.

Grafos são muito utilizados para modelar problemas em computação.

É um modelo matemático que representa relações entre objetos. Um grafo G = (V, E) consiste em um conjunto de vértices V (também chamados de nós) ligados por um conjunto de bordas ou arestas (E)

**Hello, World!**

In [53]:
tf.constant('Hello, World')

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello, World'>

# Operações com Tensores

**Soma**

In [55]:
const_a = tf.constant(5, dtype=tf.int32)
const_b = tf.constant(9, dtype=tf.int32)

print(const_a + const_b)
# ou 
print(tf.add(const_a, const_b))

tf.Tensor(14, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)


**Subtração**

In [46]:
# Criando tensor aleatório utilizando distribuição normal e com a média
# dos valores igual a 2
rand_a = tf.random.normal([3], 2.0)
rand_b = tf.random.uniform([3], 1.0, 4.0)

# print(tf.math.segment_mean(rand_a, tf.constant([0, 0, 0])))
tf.subtract(rand_a, rand_b)

tf.Tensor([ 0.48192477 -0.10165691  1.3964013 ], shape=(3,), dtype=float32)


**Divisão**

In [49]:
node1 = tf.constant(21, dtype=tf.int32)
node2 = tf.constant(7, dtype=tf.int32)

tf.math.truediv(node1, node2)

tf.Tensor(3.0, shape=(), dtype=float64)


**Multiplicação**

In [52]:
tensor_a = tf.constant([[4., 2.]])
tensor_b = tf.constant([[3.], [7.]])

# Multiplicando matrizes
tf.math.multiply(tensor_a, tensor_b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[12.,  6.],
       [28., 14.]], dtype=float32)>

**Tensor Variável X Constante**

In [60]:
tensor_variavel = tf.Variable([10, 7])
tensor_constante = tf.constant([10, 7])

# Isto daria erro!
# tensor_constante[0] = 7
tensor_variavel[0].assign(7)

tensor_variavel

# Isto também daria erro!
# tensor_constante[0].assign(7)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>